### ISSUE TITLE
Other buttons

### ISSUE THREAD

**Issue by someonefromtheinternets** [noizwaves/bootstrap-social-buttons#2]
Your buttons are great. If you're looking to extend them, this should be a list of the more common buttons used:

Weibo
Persona
Yahoo
Hyves
OpenID
Dropbox
Stack Exchange
Twitch
SoundCloud
Yandex
Vimeo

**Comment by noizwaves** [comment]
Thanks for the feedback :)

I'm keen to add more buttons / networks into the project. The limiting factor right now is icon availability in Font Awesome. I'm not married to Font Awesome for the icons, so if we could find a more comprehensive icon covering from a different icon source, I'd very much consider switching.

**Comment by someonefromtheinternets** [comment]
One that should work is Yandex, because its pictogram is just the letter "Я" in RGB 204/34/40, but I couldn't figure out the font, but the color scheme is black or red on white.

I've also created a white SVG pictogram for Weibo (https://gist.github.com/someonefromtheinternets/5673947), if you set `opacity: 0.800000011920929;` like Font Awesome does, it should look perfect.
As far as the button goes, white on red like Weibo's actual login button should work (the top is normal, the bottom one is hover): http://img.t.sinajs.cn/t5/style/images/register/form_login.png

I also found Dropbox, OpenID, Yahoo, Vimeo and Amazon (who recently started offering such an OAuth2 service as well) icons via WebHostingHub Glyphs, which work just like Font Awesome and the font used in the Bootstrap version is free under the SIL license (http://www.webhostinghub.com/glyphs/bootstrap/).

**Comment by someonefromtheinternets** [comment]
``` css
.btn-dropbox {
  color: #ffffff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
  background-color: #2181cf;
  *background-color: #2181cf;
  background-image: -moz-linear-gradient(top, #37a3eb, #2181cf);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#37a3eb), to(#2181cf));
  background-image: -webkit-linear-gradient(top, #37a3eb, #2181cf);
  background-image: -o-linear-gradient(top, #37a3eb, #2181cf);
  background-image: linear-gradient(to bottom, #37a3eb, #2181cf);
  background-repeat: repeat-x;
  border-color: #2c8ed1 #1c74b3 #0d5b97;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#37a3eb', endColorstr='#2181cf', GradientType=0);
  filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
}

.btn-dropbox:hover,
.btn-dropbox:focus,
.btn-dropbox:active,
.btn-dropbox.active,
.btn-dropbox.disabled,
.btn-dropbox[disabled] {
  color: #ffffff;
  background-color: #2389dc;
  *background-color: #2389dc;
}

.btn-dropbox:active,
.btn-dropbox.active {
  background-color: #2389dc \9;
}
```

It needs some refinements as you know better how hover and active are calculated, and it needs a custom version of the whhg.css with all other icons stripped or it will overwrite Font Awesome icons (it doesn't load before Font Awesome for some reason). Also, the WHHG icons need proper vertical alignment.
![Dropbox button](http://i.imgur.com/vlyeLoV.png)
